# Generated by Django 6.0.7 on 2026-07-14 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_change', 'Tire Change'), ('brake_service', 'Brake Service'), ('engine_repair', 'Engine Repair'), ('body_repair', 'Body Repair'), ('revision', 'Revision'), ('other', 'Other')], max_length=30)),
                ('garage', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
