# Generated by Django 6.0.7 on 2026-07-14 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Enter a valid license plate.')], verbose_name='License Plate')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('city', 'City'), ('suv', 'SUV'), ('sedan', 'Sedan'), ('utility', 'Utility'), ('luxury', 'Luxury')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('seats', models.PositiveIntegerField(default=5)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('last_revision', models.DateField(blank=True, null=True)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Price (MAD)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Security Deposit (MAD)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('maintenance_threshold', models.PositiveIntegerField(default=10000, help_text='Mileage threshold for maintenance alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
